### ISSUE TITLE
iOS build fails with new arch enabled

### ISSUE THREAD

**Issue by stevengoldberg** [margelo/react-native-worklets-core#210]
I have this library installed as a dependency of https://github.com/gev2002/react-native-vision-camera-image-labeler. I have the following package versions:

```
"react-native-vision-camera": "^4.5.2",
"react-native-vision-camera-image-labeler": "^2.2.0",
"expo": "^51.0.31",
"react-native": "0.74.5",
```

If I disable the new architecture, my project builds successfully. However, if I enable the new architecture and run `eas build`, I get the following error:

```
[INSTALL_PODS] [!] The following Swift pods cannot yet be integrated as static libraries:
[INSTALL_PODS] The Swift pod `VisionCamera` depends upon `react-native-worklets-core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
[INSTALL_PODS] [!] [Codegen] warn: using experimental new codegen integration
[INSTALL_PODS] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `A67C1F8C08C340EF9D61287B` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
[INSTALL_PODS] 
Error: pod install exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/turtle-spawn/dist/index.js:16:47)
    at installPods (/Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/ios/pod.js:12:50)
    at runInstallPodsAsync (/Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/builders/ios.js:200:70)
    at /Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/builders/ios.js:74:19
    at BuildContext.runBuildPhase (/Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/context.js:107:34)
    at buildAsync (/Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/builders/ios.js:73:19)
    at async runBuilderWithHooksAsync (/Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.iosBuilder (/Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/builders/ios.js:33:16)
    at async buildIosAsync (/Users/stevengoldberg/.npm/_npx/5e31c5d24a898acf/node_modules/eas-cli-local-build-plugin/dist/ios.js:41:12)
[CLEAN_UP_CREDENTIALS] Destroying keychain - /var/folders/l4/03vzqz3d0y1bbtryk8ckdhvw0000gn/T/eas-build-f948fd61-26a7-4145-bdd2-dc7f30aeef86.keychain
[CLEAN_UP_CREDENTIALS] Removing provisioning profile

Build failed
```

**Comment by truongnm97** [comment]
Have the same problem on `react-native@~0.75.0` and `react-native-worklets-core@^1.3.3`. Any progress on this issues?

**Comment by 5o50** [comment]
Same issue here building for new arch 

"react-native": "0.75.3",
"react-native-vision-camera": "^4.5.3",
"react-native-worklets-core": "2.0.0-beta.1",

any update ?
